use_data:
  base1:
    flip: True
  base2:
    flip: True
  base3:
    flip: True

must_train_data:
  curve1_always_center:
    flip: False
  curve1_always_in:
    flip: False
  curve1_always_out:
    flip: False
